### ISSUE TITLE
User-configutable resource directory

### ISSUE THREAD

**Issue by daniel-sanche** [Lecrapouille/gdcef#15]
Right now, the [CEF resources directory is hard-coded](https://github.com/Lecrapouille/gdcef/blob/ad2bb3dda93b4407d5bc7bf90f4bc9ecc31d4c42/addons/gdcef/gdcef/src/gdcef.cpp#L107) to be at `/build` in the godot project root. This probably doesn't make sense for most projects. And it is especially problematic for multi-platform projects, since each OS needs to read a different set of resources, which can't all be stored in the same folder.

One solution would be to allow the user to pass in a directory as part of the library initialization process

**Comment by Lecrapouille** [comment]
@daniel-sanche nice work :) I'll test it. For the few I reviewed, your code seems good.

**Comment by Lecrapouille** [comment]
I've merged them. I do not have time right now:
- for non public member variables I use `m_`
- Merging the last std::cout with GDCEF_ERROR and godot::Godot::print.
- Add in the documentation all the CEF setting/dictionary entries and add them explicitly in the demos.
- Rename the CEFHello demo to CEF2D.
- Add mouse and keyboard event to the active area in CEFHello demo.
- Add example of JS injection in demo. As a non JS-dev I do not really understand why people want to execute JS

**Comment by Lecrapouille** [comment]
@daniel-sanche Finally waiting my wife getting ready, I added time to fix several points on my list. I'll commit them to night or tomorrow.

**Comment by daniel-sanche** [comment]
Sounds good, let me know if you want me to take a look at anything on the list. I'd add:

- Add documentation for configuration dictionary fields

**Comment by daniel-sanche** [comment]
> Add example of JS injection in demo. As a non JS-dev I do not really understand why people want to execute JS

My motivation was to use it to [inject tokens to avoid a sign-in page](https://developers.home-assistant.io/docs/frontend/external-authentication/). I don't do a lot of JS either, so I'm not sure what a good demo scenario  would look like

**Comment by Lecrapouille** [comment]
@daniel-sanche 

- [DONE] for non public member variables I use `m_`
- Merging the last std::cout with GDCEF_ERROR and godot::Godot::print.
- [DONE] Add in the documentation all the CEF setting/dictionary entries and add them explicitly in the demos.
- [DONE] Rename the CEFHello demo to CEF2D.
- [DONE] Add mouse and keyboard event to the active area in CEFHello demo.
- Add example of JS injection in demo. As a non JS-dev I do not really understand why people want to execute JS

Also:

- I fixed some settings that the user shall not modify.
- You can add an example of JS in demos if you wish.
- You can help fixing my poor English sentences ;)
- I does not really like replacing `_init` by `initialize` and passing non default arguments (default dictionary will be `{}`) and CEF sub process shall be known and canonical and no more exportable. In my previous code, the path to it was directly computed, letting no risk to the user to give bad path. CEF does not pardon any error if you do not want your OS does infinite fork of processes and kill your OS.

**Comment by Lecrapouille** [comment]
Now initialize() only takes Dictionary. Ideally would be nice to use back _init() like done before and define global CEF config with the dictionary.

**Comment by daniel-sanche** [comment]
Cool, looks great! Feel free to close this issue if you think it's all done

**Comment by Lecrapouille** [comment]
Not all but mostly. let open other tickets if needed
