### ISSUE TITLE
New tab links open a new OS window

### ISSUE THREAD

**Issue by daniel-sanche** [Lecrapouille/gdcef#19]
When GDCef encounters a link that tries to open a new tab, it opens these links in new window on your OS, not in the game environment

Example: Try to click on the "Visit W3Schools.com!" link on [this page](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_link_target)

I tried to look into this, and it seems like it should be possible to override this by implementing the [OnBeforePopup](https://magpcss.org/ceforum/apidocs3/projects/(default)/CefLifeSpanHandler.html#OnBeforePopup(CefRefPtr%3CCefBrowser%3E,CefRefPtr%3CCefFrame%3E,constCefString&,constCefString&,WindowOpenDisposition,bool,constCefPopupFeatures&,CefWindowInfo&,CefRefPtr%3CCefClient%3E&,CefBrowserSettings&,CefRefPtr%3CCefDictionaryValue%3E&,bool*)) function. So far it hasn't worked for me, but I'll try to take another look at it later (unless someone else finds the fix first)

**Comment by Lecrapouille** [comment]
@daniel-sanche I see what you are talking, but your link from my Firefox and for GDCEF is displayed on the same page split vertically. Do you mean a mouse click "open in a new tab" feature?

**Comment by Lecrapouille** [comment]
@daniel-sanche I've done implementing a basic 2D browser https://github.com/Lecrapouille/gdcef/tree/master/addons/gdcef/demos/2D when creating a new browser tab it opens my favorite radio webpage, you then can click on the "Tune In" icon this will create the OS windows. Now we can try to fix it and implement a C++ method `on_popup_created` and trigger a Godot callback returning the created browser as Godot node `on_popup_created(node):`

**Comment by daniel-sanche** [comment]
Ok cool, that sounds like a good solution to me! Maybe by default it can just open the link in the current browser, if the user doesn't add the callback?

Also, when I was investigating this, it seemed to me like the CefLigfeSpanHandler functions in the GDCef Impl class weren't being called. I'm thinking maybe we need to implement GetDefaultClient() to register it as a client like in [this sample](https://bitbucket.org/chromiumembedded/cef/src/master/tests/cefsimple/simple_app.h?at=master)?

**Comment by Lecrapouille** [comment]
@daniel-sanche you are certainly right! For the moment I did not investigate

**Comment by Lecrapouille** [comment]
https://www.exaequos.com/

**Comment by Lecrapouille** [comment]
Ok if we cannot trigger the callback is because this is has to be done inside the secondary process not by the main. I'll see later.

**Comment by Lecrapouille** [comment]
Ok fixed ! Will be released soon with other fixes
