### ISSUE TITLE
Upload compiled library artifacts as part of CI

### ISSUE THREAD

**Issue by daniel-sanche** [Lecrapouille/gdcef#23]
It would be helpful to provide compiled versions of the library in the repo, either on each build, or on tagged releases.

Possible issues:
- are there licensing issues to worry about by providing the binaries?
- are there any costs for hosting the files?

**Comment by Lecrapouille** [comment]
@daniel-sanche this can be achieve. I do not like GitHub artifacts management. They are too hidden and removing them is boring. Itch.io is ok but not sure this is good location.
