### ISSUE TITLE
FileNotFoundError on compile

### ISSUE THREAD

**Issue by KianWalsh** [Lecrapouille/gdcef#29]
1) I am confident that all dependencies are met, I have python 3.11, vs, cmake, git and ninja
2) I ran py -m pip install -r requirements.txt
3) I opened x64 native tools, and cd'd into the gdcef directory 
4) I then ran py build.py from the x64 native tools terminal 
5) ERROR 

C:\Users\Kian W\Downloads\gdcef\addons\gdcef>py build.py
←[32m[INFO] Checking cmake version ...←[00m
Microsoft (R) C/C++ Optimizing Compiler Version 19.35.32215 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

win.cc
Microsoft (R) Incremental Linker Version 14.35.32215.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:win.exe
win.obj
[INFO] MS C++ Compiler OK
[INFO] Compiling Godot C++ API (inside C:\Users\Kian W\Downloads\gdcef\addons\gdcef\thirdparty\godot-3.5\cpp) ...
Traceback (most recent call last):
  File "C:\Users\Kian W\Downloads\gdcef\addons\gdcef\build.py", line 479, in <module>
    compile_godot_cpp()
  File "C:\Users\Kian W\Downloads\gdcef\addons\gdcef\build.py", line 365, in compile_godot_cpp
    run(["scons", "platform=windows", "target=" + GODOT_CPP_TARGET,
  File "C:\Users\Kian W\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kian W\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Kian W\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1493, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

any ideas, I got this to compile on ubuntu wsl, but that only generates linux files ?

**Comment by Lecrapouille** [comment]
@KianWalsh you are using Windows, right ? I ve never tested with WSL. To be sure:

- Ensure VS2022 is installed.
- Open an x64 Native Tools Command Prompt for VS 2022, with Administrator privilege (this should be available in the start menu under Visual Studio 2022). This ensures the environment is correctly set to use the VS tools.

Does that solve your case ?

**Comment by KianWalsh** [comment]
C:\Users\Kian W\Downloads\gdcef\addons\gdcef>py -m pip install scons
Requirement already satisfied: scons in c:\users\kian w\appdata\local\programs\python\python311\lib\site-packages (4.5.1)
Requirement already satisfied: setuptools in c:\users\kian w\appdata\local\programs\python\python311\lib\site-packages (from scons) (

I got scons from pip.  cmake, py and ninja in my path, and am running build.py through x64-build-tools as administator, no luck

**Comment by Lecrapouille** [comment]
@KianWalsh The line 365 is the one causing you trouble. When googling "The system cannot find the file specified subprocess.py" https://forum.codewithmosh.com/t/problem-with-subprocess-run-the-system-cannot-find-the-file-specified/17498 the guy is calling unknow command so I think scons is not callable (while installed scons cannot be found by your system).

You can try manually: Go to the subfolder godot-cpp and call:
```
scons platform=windows target=release --jobs=4
```

I guess it will fail

**Comment by Lecrapouille** [comment]
Hum ok I have too little info to find a solution. Maybe you can reach me on Discord, share your screen and type in front of me your commands in direct. this can help me finding a solution

**Comment by Lecrapouille** [comment]
I'm closing since I have not enough feedback. Reopen this ticket if needed or create a pull request if you find a solution
