### ISSUE TITLE
build.py won't finish

### ISSUE THREAD

**Issue by raphipod** [Lecrapouille/gdcef#3]
Upon downloading the newest Cef build, extracting it, the build.py script wants to compile "Godot CEF module", but it fails:
```
[INFO] Compiling Godot CEF module C:\Users\raphi\Documents\DEV\GDCef\gdcef
scons: Reading SConscript files ...

scons: *** Path for option api_path does not exist: .\godot-cpp\
File "C:\Users\raphi\Documents\DEV\GDCef\gdcef\SConstruct", line 53, in <module>
  File "C:\Users\raphi\Documents\DEV\GDCef\build.py", line 342, in <module>
    compile_gdnative_cef(GDCEF_PATH)
  File "C:\Users\raphi\Documents\DEV\GDCef\build.py", line 324, in compile_gdnative_cef
    gdnative_scons_cmd("windows")
  File "C:\Users\raphi\Documents\DEV\GDCef\build.py", line 309, in gdnative_scons_cmd
    run(["scons", "api_path=" + GODOT_CPP_API_PATH,
  File "C:\Users\raphi\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['scons', 'api_path=.\\godot-cpp\\', 'build_path=C:\\Users\\raphi\\Documents\\DEV\\GDCef\\example\\build', 'target=release', '--jobs=12', 'arch=x86_64', 'platform=windows']' returned non-zero exit status 2.
```
Scons is installed, I installed it with the requirements.txt via pip.

File structure is my [personal fork of gdcef.](https://github.com/raphipod/GDCef/tree/personal)

My wild guess is it that I need the **special environment variables** from Stigmee, am I wrong?

I really want to get this to compile completely because a web browser in Godot is just awesome!

**Comment by Lecrapouille** [comment]
@raphipod I forget to call the compile_cef() :( in the script. I've just commit it.

Ant for your issue: you have to call the script:
```
./build.py /path/to/godot/3.4.3-stable/cpp/
```
The cpp shall be compiled first. From memory:
```
git clone --recursive -b 3.4 https://github.com/godotengine/godot-cpp
cd godot-cpp
scons platform=windows target=release --jobs=8
```
I can extend my script to git clone and compile godot-cpp. For more information https://github.com/stigmee/gdnative-cef#the-godot-c-binding-api-godot-cpp (note: since I'm a beginner in Godot I'm not sure if this is the correct way of doing it).

**Comment by Lecrapouille** [comment]
@raphipod I have extended the script: I removed the path: now I cloned it and compile it. You have nothing to do now. Hope this will fix your issue

**Comment by raphipod** [comment]
Hmm. Still getting stuck at line 250, saying STIGMEE_INSTALL_PATH is not defined.

```
Traceback (most recent call last):
  File "C:\Users\raphi\Documents\DEV\GDCef\build.py", line 385, in <module>
    compile_cef()
  File "C:\Users\raphi\Documents\DEV\GDCef\build.py", line 250, in compile_cef
    shutil.copyfile(os.path.join(STIGMEE_INSTALL_PATH, "patch", "CEF", "win", "libcef_dll_wrapper_cmake"),
NameError: name 'STIGMEE_INSTALL_PATH' is not defined
```

**Comment by Lecrapouille** [comment]
@raphipod ok I know, what it this: missing copying patches for Windows. I'll commit.

**Comment by Lecrapouille** [comment]
@raphipod since I do not have Windows now I cannot really check. Ping me if something is still odd !

**Comment by raphipod** [comment]
Yes, I'll test it now!

**Comment by raphipod** [comment]
```
Traceback (most recent call last):
  File "C:\Users\raphi\Documents\DEV\GDCef\build.py", line 386, in <module>
    compile_cef()
  File "C:\Users\raphi\Documents\DEV\GDCef\build.py", line 251, in compile_cef
    shutil.copyfile(os.path.join(PATCHES_PATH, "CEF", "win", "libcef_dll_wrapper_cmake"),
  File "C:\Users\raphi\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\raphi\\Documents\\DEV\\GDCef\\gdcef\\patches\\CEF\\win\\libcef_dll_wrapper_cmake'
```
I think it expects .\patches\ in .\gdcef\, not in root folder. I am testing further.

**Comment by raphipod** [comment]
Now it stops when compiling GDNative_CEF. Something also seems odd in the SConstruct file.

```
scons: *** [src\browser_io.obj] Error 1
scons: *** [src\gdbrowser.obj] Error 1
scons: *** [src\gdcef.obj] Error 1
scons: *** [src\gdlibrary.obj] Error 1
Der Befehl "cl" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
scons: *** [src\helper.obj] Error 1
scons: building terminated because of errors.
Traceback (most recent call last):
  File "C:\Users\raphi\Documents\DEV\GDCef\build.py", line 388, in <module>
    compile_gdnative_cef(GDCEF_PATH)
  File "C:\Users\raphi\Documents\DEV\GDCef\build.py", line 371, in compile_gdnative_cef
    gdnative_scons_cmd("windows")
  File "C:\Users\raphi\Documents\DEV\GDCef\build.py", line 356, in gdnative_scons_cmd
    run(["scons", "api_path=" + GODOT_CPP_API_PATH,
  File "C:\Users\raphi\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['scons', 'api_path=C:\\Users\\raphi\\Documents\\DEV\\GDCef\\thirdparty\\godot-3.4\\cpp', 'build_path=C:\\Users\\raphi\\Documents\\DEV\\GDCef\\example\\build', 'target=release', '--jobs=12', 'platform=windows']' returned non-zero exit status 2.

```

**Comment by Lecrapouille** [comment]
@raphipod this means "The "cl" command is either misspelled or could not be found." This is your Windows g++ missing.

**Comment by raphipod** [comment]
Alright. That should be installed with Mingw, correct?

**Comment by Lecrapouille** [comment]
@raphipod nope with https://visualstudio.microsoft.com/fr/vs/ as described in the doc. More info https://github.com/stigmee/install#compile-stigmee-for-windows
I did not pick this function in this repo
See: https://github.com/stigmee/install/blob/master/build.py#L554
and https://github.com/stigmee/install/blob/master/helper.py#L203

**Comment by raphipod** [comment]
Ah, I see. I will update you tomorrow if it worked. Thanks for your help until here!

**Comment by Lecrapouille** [comment]
@raphipod courage ! On the initial project, Windows user did not get trouble: my script works well :) but on this current repo I quickly copied and adapt the script since I stopped maintaining both projects. I'll commit the cl checker function.

**Comment by raphipod** [comment]
> @raphipod courage ! On the initial project, Windows user did not get trouble: my script works well :) but on this current repo I quickly copied and adapt the script since I stopped maintaining both projects. I'll commit the cl checker function.

Ok. I'm installing cl right now, let's see what happens.

**Comment by Lecrapouille** [comment]
@raphipod I added functions for checking CMake and cl.exe

**Comment by raphipod** [comment]
Awesome! 

`[INFO] Compilation done with success. You can run your Godot editor and import the project at 'gdcef/example'`

That seemed to have worked. Can't say it a thousand times, thanks!

**Comment by Lecrapouille** [comment]
@raphipod Is this running before thanking me ?

**Comment by raphipod** [comment]
Haha. You got me there :) I'll test it with Godot

**Comment by Lecrapouille** [comment]
If this is working for you, I'll update the version to 0.3.1. I'll let you free to open pull requests for updating the unclear part of the documentation (my English is not good), upgrade the example (for example add missing key binding or applying CEF page on rotating cube). I'm a total noob in Godot :)

**Comment by raphipod** [comment]
I'll definitely update the documentation, CEF version in build.py - I also have to learn a little bit more about Godot and how it handles modules, but I'll get it working.

**Comment by Lecrapouille** [comment]
@raphipod Cool ! Is the hello world example working for you ? Just open Godot 3.4 and import the godot.project in the example/ folder.

**Comment by raphipod** [comment]
![Unbenannt](https://user-images.githubusercontent.com/56308821/180876520-7995a311-401a-479d-9c50-b1ba36f82763.PNG)

Yep, that's it. It works.

**Comment by Lecrapouille** [comment]
@raphipod Finally :)

**Comment by Lecrapouille** [comment]
Ok I'm closing this ticket. I updated the changelog to 0.3.1. I'll make a 0.3.2 if doc or example evolves.
