### ISSUE TITLE
Noob install Demo not working, Godot 4 & 3

### ISSUE THREAD

**Issue by Volk3rDE** [Lecrapouille/gdcef#38]
Hi,
0. Windows 10 x64
1. Download ZIP
2. Extract
3. Godot Import from "project.godot" from: HelloCEF, 2D or 3D
4. PLAY, and all 3 this Message and break!
5. ERROR: Invalid call: Nonexistent function "initialize" in Base "Node"
6. E 0:00:00:0623   instantiate: Cannot get class 'GDCef'.
  <C++-Fehler>   Parameter "ti" is null.
  <C++-Quelle>   core/object/class_db.cpp:358 @ instantiate()
7. W 0:00:00:0623   instantiate: Node CEF of type GDCef cannot be created. A placeholder will be created instead.
  <C++-Quelle>   scene/resources/packed_scene.cpp:254 @ instantiate()

**Comment by Lecrapouille** [comment]
@Volk3rDE Your error is a classic one (see https://github.com/Lecrapouille/gdcef/issues/36)
- For which Godot ? 3 or 4 ?
- Which zip ? The one from Github releases ?
- For Godot4 there is a gdcef.gdextension file to tell where the libs are. If its content is not correct, you'll see this error. Mine are inside libs/ folder.
- gdscript in demos tell where to find CEF artefacts. Default script behavior: see screenshots and if you export your project, the binary shall be inside the CEF artifacts.
- One demo had a broken link to CEF artefacts.
- On Windows this link needs admin rights to be created.
- Note: I also updated a lot the git to separate godot-3 and godot-4 branches (and made some git push force and one commit changes the name of the link to CEF artefacts folder).
- Now git commits are stable. You can refresh your git.

![CEF1](https://github.com/Lecrapouille/gdcef/assets/17874458/17937de7-639d-4948-a829-603ed9181c20)

![CEF2](https://github.com/Lecrapouille/gdcef/assets/17874458/f265b523-4595-478d-a1ae-a664d975dee2)

**Comment by Lecrapouille** [comment]
@Volk3rDE I close. Feel free to talk if you still have issues
