### ISSUE TITLE
Unable to build the extension for Godot 4 on Windows 11 machine

### ISSUE THREAD

**Issue by TheSilentFog** [Lecrapouille/gdcef#39]
Hi.

I followed meticulously many times the installation process found [here](https://github.com/Lecrapouille/gdcef/blob/godot-4.x/addons/gdcef/README.md) and [here](https://github.com/Lecrapouille/gdcef/blob/godot-4.x/addons/gdcef/doc/installation.md), but not once I was able to build the Godot extension.

I can't copy and past the entire stack trace since it's really too long, so this is the last part of stack trace I get:
```
C:\Users\loren\Desktop\Godot Projects\GDCEF Test\addons\gdcef\thirdparty\cef_binary\tests\ceftests\Release\ceftests.exe
 : fatal error LNK1169: rilevato uno o più simboli definiti più volte [C:\Users\loren\Desktop\Godot Projects\GDCEF Test
\addons\gdcef\thirdparty\cef_binary\tests\ceftests\ceftests.vcxproj]
Traceback (most recent call last):
  File "C:\Users\loren\Desktop\Godot Projects\GDCEF Test\addons\gdcef\build.py", line 500, in <module>
    compile_cef()
  File "C:\Users\loren\Desktop\Godot Projects\GDCEF Test\addons\gdcef\build.py", line 294, in compile_cef
    run(["cmake", "--build", ".", "--config", CEF_TARGET], check=True)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release']' returned non-zero exit status 1.
```

I would like to point out that the third line of the installation process `./build.py` doesn't work on my machine and I had to fix it to `python3 ./build.py`.

If you need to know more details, just ask.
Thank you in advance.

**Comment by raphipod** [comment]
Basically the Python script exits because it couldn't execute the cmake command with the **subprocess** python module.

Check if cmake is installed on your system. Should be getting installed with Visual Studio C++

https://learn.microsoft.com/de-de/cpp/build/media/cmake-install-2019.png?view=msvc-170

This option should be checked in the Visual Studio Installer.


I will debug this as soon as I get a VM running with Windows, as I no longer use Windows as my main OS.

**Comment by Lecrapouille** [comment]
Hi ! 

- @TheSilentFog you are using the godot-4 branch. Yes please add the whole console content in a file in your ticket. That can help. You can also try to follow logs of the CI that is passing https://github.com/Lecrapouille/gdcef/actions/runs/7515818505/job/20460321996
- Concerning "python3 ./build.py" the script starts with "#!/usr/bin/env python3" for Linux users. As Raphipod said Windows does not manage "./". I'll rephrase my doc.
- @raphipod This is not a "cmake missing" issue because I checked it if it exists:
```
def check_cmake_version():
    DOC_URL = "https://github.com/stigmee/doc-internal/blob/master/doc/install_latest_cmake.sh"
    info("Checking cmake version ...")
    if shutil.which("cmake") == None:
        fatal("Your did not have CMake installed. For Linux see " + DOC_URL +
              " to update it before running this script. For Windows install "
              "the latest exe.")
```
(but maybe on Windows `shutil.which` does not work)

- `rilevato uno o più simboli definiti più volte` means symbols are defined several times. @TheSilentFog are you on the HEAD ? Try to update your git branch. I do not remember what kind of errors if the patch `gdcef/addons/gdcef/patches/CEF/win/libcef_dll_wrapper_cmake` is not applied. @BlayTheNinth initially removed this patch when he made CEF working for Godot4, I added the patch back.

**Comment by TheSilentFog** [comment]
@raphipod According to VS Installer CMAKE was installed, but since you pointed out that the problem could be around CMAKE, I inspected the programs installed on my machine and tada!, I found out that I had two of them installed.

So, since I'm on windows and the resulting behaviour could be unexpected and I don't like doing things erratically. I uninstalled both the CMAKE double and the entire Visual Studio C++ for Desktop development inside VS installer.
After a reboot I followed step by step again the installation process, checking the things already installed that were already working, installing what was missing and rebooting again.

Unfortunately for me the building process didn't work again, and unfortunately for you @Lecrapouille, I can't get the whole console content now.
I'm sorry my friend, I read your comment too late.

Now I'm stuck with this stack trace:
```
C:\Users\loren\Desktop\Godot Projects\GDCEF Test\addons\gdcef>python3 ./build.py
←[32m[INFO] Checking cmake version ...←[00m
Traceback (most recent call last):
  File "C:\Users\loren\Desktop\Godot Projects\GDCEF Test\addons\gdcef\build.py", line 495, in <module>
    check_cmake_version()
  File "C:\Users\loren\Desktop\Godot Projects\GDCEF Test\addons\gdcef\build.py", line 462, in check_cmake_version
    if version.parse(current_version) < version.parse(CMAKE_MIN_VERSION):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\loren\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\packaging\version.py", line 54, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\loren\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\packaging\version.py", line 200, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '3.27.2-msvc1'
```

Seems it wasn't able to parse my cmake version, so:
```
C:\Users\loren\Desktop\Godot Projects\GDCEF Test\addons\gdcef>cmake --version
cmake version 3.27.2-msvc1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

Thank you @Lecrapouille for the link to the precompiled release, I haven't tried it yet but it should solve my problems and headaches. It doesn't help solving your building problems on windows though.
So, if you find it useful, I'm willing to go on with the building process, until it manages to build.

**Comment by raphipod** [comment]
Hmm. 

Just to clarify: There is an upstream CMake available to download, and the one that gets installed with the C++ desktop development package in Visual Studio (for Windows).

We should probably focus on the CMake version from VS as we already use the C++ desktop dev package.

https://github.com/Lecrapouille/gdcef/blob/bb008a229dfb5a17b3eabe072829c888812343be/addons/gdcef/build.py#L461-L471

The snippet of the build script here tries to compare the installed CMake's version number with the minimal version number, which is 3.19.
As the included CMake of VS seemingly is at 3.27.2, we don't have any issue atleast on Windows.

For outdated or slow-updating Linux distros the version check (last lines) is applicable, but for Windows, we can almost be sure that the version is >3.19.

What if we add a third check at L468 that the if-function only gets executed on Linux platform? @Lecrapouille

@TheSilentFog comment out lines 468-471, run it again, and see if it makes any difference. That would be my next step.

**Comment by TheSilentFog** [comment]
I commented the lines and gave it a try.
The resulting behaviour is the same as the start of this issue.

Here the entire stack trace as requested: [StackTrace.txt](https://github.com/Lecrapouille/gdcef/files/14052487/StackTrace.txt)

**Comment by Lecrapouille** [comment]
@TheSilentFog 

```
cef_sandbox.lib(check_op.obj) : error LNK2038: rilevata errata corrispondenza per 'RuntimeLibrary': il valore 'MT_StaticRelease' non corrisponde al valore 'MD_DynamicRelease' in binary_transfer_test.ob
```

Ok I think I understood: You have initially compiled CEF when the application of the windows patch has been removed (during the initial commit): your CEF was compiled as dynamic lib. Then you have updated the git which has added the patch back (for compiling CEF has static lib), this mess up the compiler: it is lost between dynamic and static symbols. Remove the cef_binary in `gdcef/addons/gdcef/thirdparty` and launch back build.py script, this will compile correctly.
