### ISSUE TITLE
Integrating JavaScript APIs

### ISSUE THREAD

**Issue by Lecrapouille** [Lecrapouille/gdcef#40]
Requested by @punto- https://godotengine.org/article/godot-web-progress-report-9/

**Comment by pimhakkert** [comment]
I'm curious if there is still interest in something like this. If enough requests are made and some valid examples can be made that can't be solved by a simple Godot <-> JavaScript string transfer, I'll consider working on this.

**Comment by Lecrapouille** [comment]
@pimhakkert

https://github.com/folgerwang/UnrealEngine/blob/release/Engine/Source/Runtime/WebBrowser/Private/CEF/CEFJSScripting.cpp#L42

**Comment by Lecrapouille** [comment]
@eliopark-nsuslab I'm giving a try implementing JS bindings https://github.com/Lecrapouille/gdcef/tree/wip-js, but currently, OnContextCreated is never called, so I'm stuck. On what parts are you working on ?

**Comment by Lecrapouille** [comment]
@punto- ok after almost 1 year I succeeded to bind JS function to Godot. Initial commit on a button click, lot of work to do but I have made the most difficult part :)

**Comment by Lecrapouille** [comment]
![Capture d’écran_2024-12-09_01-35-46](https://github.com/user-attachments/assets/69ac904e-5c09-40a1-bb17-f174802c0825)
![Capture d’écran_2024-12-09_01-31-30](https://github.com/user-attachments/assets/0924c7b5-08de-4887-b16e-968b25c299e0)
![Capture_decran_2024-12-08_20-50-51](https://github.com/user-attachments/assets/e77f75df-bf88-4f68-898a-4e8fa00aa28f)
![Capture_decran_2024-12-08_20-51-29](https://github.com/user-attachments/assets/99c3a12c-f71d-4e11-933a-6c3db8a93bee)

**Comment by Lecrapouille** [comment]
I'm using a JS proxy, new syntax:

![Capture d’écran_2024-12-09_19-45-03](https://github.com/user-attachments/assets/4b2871ad-7ecc-42ac-96cc-9a62c7ab3a09)

**Comment by Lecrapouille** [comment]
Added new demo https://github.com/Lecrapouille/gdcef/tree/godot-4.x/addons/gdcef/demos#demo-03-cef-browser-in-2d-with-js-bindings

For the moment only JS => gdscript. I'll do the other side.

![JS bindings](https://github.com/user-attachments/assets/18b76d18-e7fe-4766-850c-7b8ae39db957)

**Comment by lran-git** [comment]
Thanks a lot for the solid work, really helps. 
I'm trying to use gdcef for ui, both js <=> gdscript are needed. I followed the js bindings demo, and did some tests on my own, so far, gdscript => js works without problems, but for js => gdscript, params of type string | int | float | bool work as expected, params of type array | object turn to empty string.

```
// js code, in an iframe
if (window.parent.godot && window.parent.godot._on_browser_called) {
    window.parent.godot._on_browser_called({"text": "info from browser", "key": "k1"});
    window.parent.godot._on_browser_called(["hello world!", 111]);
    window.parent.godot._on_browser_called("hello world!");
    window.parent.godot._on_browser_called(1500);
    window.parent.godot._on_browser_called(1.33333);
    window.parent.godot._on_browser_called(true);
}
```

```
# godot cef binding setup
func _on_page_loaded(browser):
	# Register methods for JS->Godot communication
	browser.register_method(_on_browser_called)

func _on_browser_called(info):
	print("info: {0}, type: {1}".format([info, typeof(info)]))
```

```
# results
info: , type: 4
info: , type: 4
info: hello world!, type: 4
info: 1500, type: 2
info: 1.33333, type: 3
info: true, type: 1
```

Object and array as param really useful, please take a look, thanks a lot again!

**Comment by Lecrapouille** [comment]
Thank you for the report. This was made quickly and without unit tests so yes this is probably currently broken. I will check.

**Comment by Lecrapouille** [comment]
@lran-git should be fixed. Please update the HEAD of godot-4 branch and test. If OK I will create a release. Please join the discord. I'm interested by which HTML gui you are making.

**Comment by lran-git** [comment]
Now param of object or array works as expected, thanks a lot.
I’m currently working on integrating an AI agent system as the backend, allowing users to interact with the Godot app through chat. If I can use stream chat webui within godot and bind to existing functions, I won’t need to rebuild ui from scratch—saving time.

Unfortunately, I can’t use Discord easily due to regional restrictions. Apologies!

**Comment by Lecrapouille** [comment]
@lran-git yes ok that it's strange to use Godot but why not. Send me a picture of your application and the link once done. I'll promote it in the gallery

**Comment by lran-git** [comment]
@Lecrapouille will do, thanks again.
