### ISSUE TITLE
audio bus output

### ISSUE THREAD

**Issue by Loudened** [Lecrapouille/gdcef#42]
This is really awesome. The best CEF attempt so far :)
Is there a way to grab the audio stream from CEF and pipe it through a Godot audio bus,  so that we can make it 3d positional?

**Comment by Lecrapouille** [comment]
@Loudened maybe this commit https://github.com/Lecrapouille/gdcef/pull/31 but since I git rebased the project GitHub failed showing the diff, but the PR did not pass my code review lol. Here is the initial commit https://github.com/pixaline/gdcef/commit/e99d5b1743ed701468743417e98a5f0a5ad9eb67**

**Comment by Loudened** [comment]
Ah yes! This looks like exactly what I mean.
Although also looks like it's not compatible with the current branch and no-one has worked on it for some time  :(

**Comment by Lecrapouille** [comment]
It's working I added @pixaline PR but currently, I cannot swap between pure CEF audio and routing audio to Godot. Once one is selected, we cannot swap to second mode.

**Comment by Lecrapouille** [comment]
@Loudened I committed in branch https://github.com/Lecrapouille/gdcef/tree/dev-audio-routing tell me if OK for you I'll merge in main branches.

**Comment by Lecrapouille** [comment]
Oups! in this branch my C++ got a typo inside a "if" and Godot segfault. I will merge routing sound in the godot-4 branch

**Comment by Loudened** [comment]
Thank you @Lecrapouille
