### ISSUE TITLE
Not able to get jitsi-meet works in the 2D demo

### ISSUE THREAD

**Issue by GeorgeS2019** [Lecrapouille/gdcef#49]
Wonder what is missing?

**Comment by Lecrapouille** [comment]
@GeorgeS2019 without context, difficult to tell you. I know ffmpeg hd264 is not given by default in CEF prebuilds. I know my plugin is suffering with page using massive webasm code such as https://www.exaequos.com/

**Comment by GeorgeS2019** [comment]
For jitsi-mmet to work, 
it request permission to microphone and video.   
In the 2D demo, no such request.

**Comment by GeorgeS2019** [comment]
For a folder with index.html and the javascript to be loaded, will the javascript be loaded?

**Comment by Lecrapouille** [comment]
@GeorgeS2019 Ok i reproduce it. Probably correlated with https://github.com/Lecrapouille/gdcef/issues/19.
For the second question: no. https://github.com/Lecrapouille/gdcef/issues/40

**Comment by GeorgeS2019** [comment]
@Lecrapouille 
What if the javascript is embeded within the html ?

**Comment by GeorgeS2019** [comment]
@Lecrapouille 
Thx for making so much progress with the Godot4 CEF browser.

**Comment by Lecrapouille** [comment]
I see what I have to write but the callback is not triggered. I'm not sure if I placed it correctly

**Comment by GeorgeS2019** [comment]
thx for trying. Imagine Jitsi is possible in Godot4. It will be game chaning.

Unity already has Jitsi.  Just google it.

**Comment by Lecrapouille** [comment]
@GeorgeS2019 Note you need to comment the _on_page_failed_loading I dunno why some pages entered on this callback including jitsi

**Comment by GeorgeS2019** [comment]
there is no windows artifact. I wait

**Comment by Lecrapouille** [comment]
@GeorgeS2019 I'm not sure to understand what you said. I did not start a meeting (since I had no friends to call lol) but I saw my webcam was working at least on Linux. You can update your project from this repo (the change is not yet available on Godot asset store) and try the demo2D I added the new settings to allow using camera and microphones.

**Comment by GeorgeS2019** [comment]
It is not trivial build, so I wait

**Comment by Lecrapouille** [comment]
@GeorgeS2019 Ok I can tag 0.8.1 or 0.9.0 the CI will create artifacts https://github.com/Lecrapouille/gdcef/releases

**Comment by GeorgeS2019** [comment]
Sorry for making your holiday short

**Comment by Lecrapouille** [comment]
@GeorgeS2019 tested in future version 1.20: working
