### ISSUE TITLE
CEF 104 failed with Linux

### ISSUE THREAD

**Issue by Lecrapouille** [Lecrapouille/gdcef#5]
@raphipod I reverted CEF version to 103 it seems that on my Debian I have a failure. I have to investigate.

**Comment by Lecrapouille** [comment]
@raphipod I have also added a new demo + used Godot-3.5, is this working for you ?

**Comment by raphipod** [comment]
Well, what a coincidence. I am on Fedora right now, I'm setting it up right now. Afterwards I'll test it!

**Comment by Lecrapouille** [comment]
@raphipod I emailed you. The issue is `CefInitialize failed` I guess it's because the `build/gdcefSubProcess` is broken: it is supposed to run as a standalone application, but it's frozen.

**Comment by raphipod** [comment]
I've successfully compiled gdcef from your master branch with CEF 103 (with Fedora 36), I have yet to test it with Godot 3.5

**Comment by raphipod** [comment]
Hmm. When I try to run CEF.tscn in /examples/01/, it spits out the following:

`Invalid call. Nonexistent function 'create_browser' in Node`

It errors out in the CEF node, the gdnlib script is attached, but it shows up as empty in the editor:

![Bildschirmfoto vom 2022-08-15 22-25-48](https://user-images.githubusercontent.com/56308821/184712448-d5c87b71-8d7f-48d8-8673-9de0ef2aa5a6.png)

**Comment by raphipod** [comment]
> @raphipod I emailed you. The issue is `CefInitialize failed` I guess it's because the `build/gdcefSubProcess` is broken: it is supposed to run as a standalone application, but it's frozen.

Ok. I'll continue working on this tomorrow. I'll write something if I got news.

**Comment by Lecrapouille** [comment]
@raphipod the main scene is `gui_in_3d`

**Comment by raphipod** [comment]
So, CEF 104 successfully compiled on my Fedora machine. A wild guess: They've probably changed something in the backend of CEF that a development package of Debian can not provide due to a newer version of it being needed.

**Comment by Lecrapouille** [comment]
@raphipod closed. Tried with the newer CEF 104 has fixed issues or more probable the issue was on my side with LD_LIBRARY_PATH referring to an older CEF version
