### ISSUE TITLE
Communicating data between gdscript <-> browser

### ISSUE THREAD

**Issue by 3ddelano** [Lecrapouille/gdcef#51]
Is there a way I can send data from the browser side (javascript) to my gdscript and vice-versa?
For example: If a html textbox is typed into can i get the data typed in gdscript?

**Comment by Lecrapouille** [comment]
Hi @3ddelano the current way to interact with JS is given line

https://github.com/Lecrapouille/gdcef/blob/6f00652a97ad75af31e2d247bcb2ddf055ecbfc8/addons/gdcef/demos/2D/CEF.gd#L175

But you cannot get feedback from JS. This is a request https://github.com/Lecrapouille/gdcef/issues/40

**Comment by 3ddelano** [comment]
Oh thanks for the reply. Right now to get feedback from js im using a http server running in gdscript and the js makes API calls to the server. This works but needs a lot more code to setup.

**Comment by pimhakkert** [comment]
@3ddelano Using a HTTP server adds a lot of overhead as well. I'm working on a feature that will let you communicate easily between GDscript and the browser via a message protocol. You can use that to transfer JSON strings with instructions for each side as an example.

**Comment by 3ddelano** [comment]
Oh nice

**Comment by berkaycimsir** [comment]
> @3ddelano Using a HTTP server adds a lot of overhead as well. I'm working on a feature that will let you communicate easily between GDscript and the browser via a message protocol. You can use that to transfer JSON strings with instructions for each side as an example.

Do you have any update on this ?

**Comment by Lecrapouille** [comment]
@berkaycimsir for the moment no.

**Comment by berkaycimsir** [comment]
> @berkaycimsir for the moment no concerning @pimhakkert

Can you think of any shortcout way for this right now ?

I was able to send data from godot to my browser via [MessageChannel ](https://developer.mozilla.org/en-US/docs/Web/API/MessageChannel) but couldn't find a way to do it from browser to godot side.

**Comment by Lecrapouille** [comment]
@berkaycimsir can you go to my gdcef discord https://discord.gg/EckEwy7S5U to show me a simple example of what you have made ? I need a basic example since I'm not a webdev.

**Comment by Lecrapouille** [comment]
Closing, following the conversion on https://github.com/Lecrapouille/gdcef/issues/40
