### ISSUE TITLE
CAN i use C# with this addon？

### ISSUE THREAD

**Issue by chutianshu1981** [Lecrapouille/gdcef#53]
CAN i use C# with this addon？
Please tell me how

**Comment by Lecrapouille** [comment]
@chutianshu1981 Sorry there is not C# version of it. Do you mean https://github.com/cefsharp/CefSharp ? There are 2 different projects. I've never worked for CefSharp, their API is probably more mature than mine but they do not manage Godot. On my side I'm not C# user.

**Comment by Lecrapouille** [comment]
I close this ticket since I cannot do something for you, sorry. We can keep talking if you want.
