### ISSUE TITLE
Feature request: Android exports for VR Quest WebViews

### ISSUE THREAD

**Issue by garred** [Lecrapouille/gdcef#61]
Is there any chance to have these webviews working in android applications? Specifically I'm looking for VR/AR Quest android exports.

I already tried but get runtime errors:

```
W 0:00:00:0964   instantiate: Node CEF of type GDCef cannot be created. A placeholder will be created instead.
  <C++ Source>   scene/resources/packed_scene.cpp:254 @ instantiate()
```

I would like to help implementing this feature but I'm quite lost about where to start, and probably not even skilled enough.

**Comment by Lecrapouille** [comment]
Hi @garred afaik CEF is not working for phone devices. Therefore gdcef will not work neither. Concerning the documentation I made some effort on writing it 😪 Feel free to talk about unclear point. My English is not good

**Comment by Lecrapouille** [comment]
Try opening an issue to CEF project for requesting phone devices

**Comment by Lecrapouille** [comment]
https://magpcss.org/ceforum/viewtopic.php?f=6&t=18268
