### ISSUE TITLE
open a new frame ,can not get infomation

### ISSUE THREAD

**Issue by wangluodaxia** [Lecrapouille/gdcef#67]
![image](https://github.com/user-attachments/assets/b38edd1f-36e3-469d-9bb8-fd8bb28f0864)

![image](https://github.com/user-attachments/assets/617d42ba-c0fa-4973-99ef-64c12cf241a9)
 should get new frame information

**Comment by wangluodaxia** [comment]
![image](https://github.com/user-attachments/assets/cd1f5cf0-ee1b-4d52-8cf8-912fbcd59e78)

**Comment by Lecrapouille** [comment]
Ah ok I take the point: related with #19 I'm not sure to solve this. I do not know if there is a callback triggered before the frame is created. If it exists I should create a new Godot texture and store it as child node, create a new browser view and normally the callback will pass the expected frame. Hard work.

**Comment by Lecrapouille** [comment]
Fixed but, CEF got weird page disposition (which is another issue)
