### ISSUE TITLE
Godot 4.3 doesn't recognize de plugin

### ISSUE THREAD

**Issue by ChairmanChairXD** [Lecrapouille/gdcef#69]
I try to install in the assets store, but when i open project settings, the plugin isn't there

**Comment by Lecrapouille** [comment]
@ChairmanChairXD ok Ill check. Untill now I only rested/used Godot 4.2

**Comment by Lecrapouille** [comment]
@ChairmanChairXD I tried with Godot 4.2 and 4.3, the gdcef folder is downloaded correctly inside the folder addons. I did not get the point with your "project settings" I'm a Godot noob. You have to call the `addons/gdcef/build.py` to compile (and maybe edit it to set Godot 4.3) and obtain the build folder `cef_artifacts`. Else you can try prebuild artifcats https://github.com/Lecrapouille/gdcef/releases

**Comment by Lecrapouille** [comment]
@ChairmanChairXD ah ok I understand, after seeing a plugin having it. I missed the cfg and a dummy gd file. I can add them but I'm not sure this is really a need for this plugin maybe fixing https://github.com/Lecrapouille/gdcef/issues/41

**Comment by Lecrapouille** [comment]
@ChairmanChairXD Available in release https://github.com/Lecrapouille/gdcef/releases/tag/v0.11.0-godot4
