### ISSUE TITLE
Godot 4.2.2 reports GDExtension library not found

### ISSUE THREAD

**Issue by Endermanbugzjfc** [Lecrapouille/gdcef#70]
# Attempts
Thinking that installing the built version would be easier, I downloaded the latest source version (0.10.0-godot4) on AssetLib page before running into the following error:
```
core/extension/gdextension.cpp:688 - GDExtension library not found: 
  Failed loading resource: res://cef_artifacts/gdcef.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
```

Then, I tried using the built version on your release page but got the same result again. I also edited the .gdextension file by updating the paths that it points at and hoped it would work. Sadly it didn't. Here are that paths that I tested:
# .gdextension samples
```
[configuration]
entry_symbol = "gdcef_library_init"
compatibility_minimum = 4.1

[libraries]
linux.x86_64.debug = "res://cef_artifacts/libgdcef.so"
linux.x86_64.release = "res://cef_artifacts/libgdcef.so"
linux.x86_32.debug = "res://cef_artifacts/libgdcef.so"
linux.x86_32.release = "res://cef_artifacts/libgdcef.so"

windows.x86_64.debug = "res://libgdcef.dll"
windows.x86_64.release = "res://libgdcef.dll"
windows.x86_32.debug = "res://libgdcef.dll"
windows.x86_32.release = "res://libgdcef.dll"

macos.debug = "res://cef_artifacts/Frameworks/Chromium\ Embedded\ Framework.framework/Libraries/libgdcef.dylib"
macos.release = "res://cef_artifacts/Frameworks/Chromium\ Embedded\ Framework.framework/Libraries/libgdcef.dylib"
```
```
[configuration]
entry_symbol = "gdcef_library_init"
compatibility_minimum = 4.1

[libraries]
linux.x86_64.debug = "res://cef_artifacts/libgdcef.so"
linux.x86_64.release = "res://cef_artifacts/libgdcef.so"
linux.x86_32.debug = "res://cef_artifacts/libgdcef.so"
linux.x86_32.release = "res://cef_artifacts/libgdcef.so"

windows.x86_64.debug = "res://gdcef/gdcef.dll"
windows.x86_64.release = "res://gdcef/gdcef.dll"
windows.x86_32.debug = "res://gdcef/gdcef.dll"
windows.x86_32.release = "res://gdcef/gdcef.dll"

macos.debug = "res://cef_artifacts/Frameworks/Chromium\ Embedded\ Framework.framework/Libraries/libgdcef.dylib"
macos.release = "res://cef_artifacts/Frameworks/Chromium\ Embedded\ Framework.framework/Libraries/libgdcef.dylib"
```
```
[configuration]
entry_symbol = "gdcef_library_init"
compatibility_minimum = 4.1

[libraries]
linux.x86_64.debug = "res://cef_artifacts/libgdcef.so"
linux.x86_64.release = "res://cef_artifacts/libgdcef.so"
linux.x86_32.debug = "res://cef_artifacts/libgdcef.so"
linux.x86_32.release = "res://cef_artifacts/libgdcef.so"

windows.x86_64.debug = "res://addons/gdcef/gdcef.dll"
windows.x86_64.release = "res://addons/gdcef/gdcef.dll"
windows.x86_32.debug = "res://addons/gdcef/gdcef.dll"
windows.x86_32.release = "res://addons/gdcef/gdcef.dll"

macos.debug = "res://cef_artifacts/Frameworks/Chromium\ Embedded\ Framework.framework/Libraries/libgdcef.dylib"
macos.release = "res://cef_artifacts/Frameworks/Chromium\ Embedded\ Framework.framework/Libraries/libgdcef.dylib"
```
# Notes
I have looked at Godot's [source code](https://github.com/godotengine/godot/blob/7fbfe1dbe73916f95ee5c022e7defb0c25c240fb/core/extension/gdextension.cpp#L688) and found out it was supposed to follow a library path after the error which was not my case. Therefore, I suspect if it is an error in the game engine itself.

I tested with version 0.9.0 as well but things did not change much. I am not a CPP programmer, so I cannot deal with this alone.

I appreciate your effort on this project and hope it will work on everyone's machine.

# Environment
Godot: **4.2.2**
Operating system: **Windows 11 21H2 Build 22000.1936**
Project renderer: **Compatibility**

**Comment by Lecrapouille** [comment]
@Endermanbugzjfc just for information, the latest release is 0.11.0 for Godot 4.3 https://github.com/Lecrapouille/gdcef/releases/tag/v0.11.0-godot4 it contains the cef_artifacts. The Godot asset lib will download code source that you have to compile by yourself.

For Windows we have to fix this issue https://github.com/Lecrapouille/gdcef/issues/45 but for exported projects.

Have you tried the demos (gdcef/addons/gdcef/demos/2D/) ? They shall work directly (if you have compiled gdcef by yourself), else copy the cef_artifacts inside each demos. You do not have to modify the .gdextension normally since version 0.10.0.

Afaik I do not have Windows, and virtualbox on Linux cannot help me testing gdcef once compiled, so I cannot help a lot.

**Comment by Endermanbugzjfc** [comment]
Tysm! It operates correctly after updating to Godot 4.3.

**Comment by Lecrapouille** [comment]
@Endermanbugzjfc Thank you the first good news of the day :)
