### ISSUE TITLE
Wrong folder organisation

### ISSUE THREAD

**Issue by Lecrapouille** [Lecrapouille/gdcef#8]
@raphipod This project is now on the Godot asset lib https://godotengine.org/asset-library/asset/1426 I tagged it as `2D tools` but I just realized that I should have placed all contents inside a `addons/gdcef` folder. Since i'm noob in Godot, raphipod can you confirm ?

**Comment by raphipod** [comment]
Yep, it dumps all gdcef files in the project root instead of in /addons/gdcef, as you said.

**Comment by MGilleronFJ** [comment]
It would be cleaner if all necessary files were undert `addons/gdcef`. Also, you have other files around which users have to check/uncheck before installing the plugin. I suggest you add a `.gitattributes` to your repo to exclude these files so when the assetlib downloads your plugin Github will make a zip package containing only what's necessary. See https://github.com/Zylann/godot_heightmap_plugin/blob/master/.gitattributes

**Comment by Lecrapouille** [comment]
@MGilleronFJ thank you ! Nice to have confirmation ! I'll do it after my holidays in a couple of days !

**Comment by Lecrapouille** [comment]
@MGilleronFJ since I cannot currently test on Linux I made a commit on the dev-refacto branch. Does this seem fine for you ?

**Comment by Lecrapouille** [comment]
Merged to master. I'll clean the doc and upload again on the store. Feel free to open a new ticket.
