### ISSUE TITLE
No SConstruct file found

### ISSUE THREAD

**Issue by nUKEmAN4** [Lecrapouille/gdcef#9]
```
[INFO] MS C++ Compiler OK
[INFO] Compiling Godot C++ API (inside C:\Users\PC\Desktop\Browser\thirdparty\godot-3.5\cpp) ...

scons: *** No SConstruct file found.
File "D:\Program Files\Python310\lib\site-packages\SCons\Script\Main.py", line 945, in _main
Traceback (most recent call last):
  File "C:\Users\PC\Desktop\Browser\build.py", line 465, in <module>
    compile_godot_cpp()
  File "C:\Users\PC\Desktop\Browser\build.py", line 361, in compile_godot_cpp
    run(["scons", "platform=windows", "target=" + GODOT_CPP_TARGET,
  File "D:\Program Files\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['scons', 'platform=windows', 'target=release', '--jobs=4']' returned non-zero exit status 2.
```

When I try to build im getting this error.

**Comment by Lecrapouille** [comment]
@nUKEmAN4 Hi ! I guess this error is when you are compiling godot-cpp for Windows, right ? Is the git clone ended correctly ? Do you see godot-3.5 in the folder `gdcef/thirdparty` ?

**Comment by nUKEmAN4** [comment]
I managed to fix that error, it says compilation success open example in godot... and when I open I'm getting this error in godot: 

```
E 0:00:00.373   init_library:  does not have a library for the current platform.
  <C++ Error>   Condition "lib_path.length() == 0" is true.
  <C++ Source>  modules/gdnative/nativescript/nativescript.cpp:1479 @ init_library()
```

**Comment by Lecrapouille** [comment]
@nUKEmAN4 sadly I do not have Windows for testing and I realized that my gdcef.gdnlib and gdcef.gdns did not refer to the .dll, I tried to fixed it on master but I cannot check my change. Also inside the Godot editor on the CEF node you can try to suppress and add back the libs/gdcef.gdns file I may have forget on one of my example to refresh the path. If not solved you can check if the path to the dll is correct.

**Comment by nUKEmAN4** [comment]
Sadly, still same error.

**Comment by Lecrapouille** [comment]
@nUKEmAN4 Are you on the master ? Can you check the path of your build folder is gdcef/examples/build/ and check if the gdcef/examples/00/build is an alias to gdcef/examples/build/ and what do you see inside?

**Comment by Lecrapouille** [comment]
@nUKEmAN4 feel free to open back the issue if needed
